---
abstract: 'Attribute that makes overloading easier'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-Overload
provides:
  Attribute::Overload:
    file: lib/Attribute/Overload.pm
    version: 1.100710
requires:
  Attribute::Handlers: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Attribute-Overload
  homepage: http://search.cpan.org/dist/Attribute-Overload/
  repository: http://github.com/hanekomu/Attribute-Overload
version: 1.100710
